pipeline {
    agent any
    tools{
        jdk 'java-17'
        maven 'maven-3'
    }
    stages{
        stage('compile'){
            steps{
                dir('Boardgame-main'){
                    sh 'mvn compile'
                }
            }
        }
        stage('test'){
            steps{
                dir('Boardgame-main'){
                    sh 'mvn test'
                }
            }
        }
        stage('build'){
            steps{
                dir('Boardgame-main'){
                    sh 'mvn package'
                }
            }
        }
    }
}
